/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminSettings {
  key: string;
  updated_at: Generated<Timestamp | null>;
  value: Json;
}

export interface AiMessages {
  content: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string | null>;
  role: string | null;
  user_id: Generated<string | null>;
}

export interface AnalyticsEvents {
  created_at: Generated<Timestamp | null>;
  event_data: Json | null;
  event_name: string | null;
  id: Generated<string | null>;
  user_id: Generated<string | null>;
}

export interface BodyMapResponses {
  activity_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string | null>;
  pass: string | null;
  user_id: Generated<string | null>;
  zones_selected: string[] | null;
}

export interface Categories {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string | null>;
  name: string | null;
  name_en: string | null;
  parent_id: Generated<string | null>;
  slug: string | null;
  sort_order: number | null;
}

export interface DateResponses {
  answer: string | null;
  created_at: Generated<Timestamp | null>;
  date_id: Generated<string | null>;
  id: Generated<string | null>;
  scene_id: Generated<string | null>;
  user_id: Generated<string | null>;
}

export interface Dates {
  created_at: Generated<Timestamp | null>;
  id: Generated<string | null>;
  initiator_id: Generated<string | null>;
  mood: string | null;
  partnership_id: Generated<string | null>;
  scheduled_for: Timestamp | null;
  status: string | null;
}

export interface DiscoveryConfig {
  config_type: string | null;
  created_at: Generated<Timestamp | null>;
  data: Json | null;
  id: Generated<string | null>;
  is_active: boolean | null;
  updated_at: Generated<Timestamp | null>;
  version: number | null;
}

export interface ExcludedPreferences {
  category_id: Generated<string | null>;
  excluded_at: Generated<Timestamp | null>;
  excluded_tag: string | null;
  exclusion_level: string | null;
  id: Generated<string | null>;
  reason: string | null;
  reconsider_after_days: number | null;
  user_id: Generated<string | null>;
}

export interface ExperienceResponses {
  created_at: Generated<Timestamp | null>;
  experience_rating: string | null;
  has_tried: boolean | null;
  id: Generated<string | null>;
  scene_id: Generated<string | null>;
  user_id: Generated<string | null>;
  want_to_try: boolean | null;
}

export interface HiddenStorageImages {
  filename: string | null;
  hidden_at: Generated<Timestamp | null>;
  id: Generated<string | null>;
}

export interface ImageAnalysis {
  analysis: Generated<Json>;
  created_at: Generated<Timestamp | null>;
  file_name: string;
  file_url: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface OrientationWishlist {
  created_at: Generated<Timestamp | null>;
  email: string | null;
  id: Generated<string | null>;
  requested_orientation: string | null;
  user_id: Generated<string | null>;
}

export interface PartnerChatMessages {
  content: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string | null>;
  partner_id: Generated<string | null>;
  role: string | null;
  user_id: Generated<string | null>;
}

export interface Partnerships {
  created_at: Generated<Timestamp | null>;
  id: Generated<string | null>;
  invite_code: string | null;
  inviter_id: Generated<string | null>;
  nickname: string | null;
  partner_id: Generated<string | null>;
  status: string | null;
  user_id: Generated<string | null>;
}

export interface PreferenceProfiles {
  id: Generated<string | null>;
  preferences: Json | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface Profiles {
  created_at: Generated<Timestamp | null>;
  gender: string | null;
  id: Generated<string | null>;
  interested_in: string | null;
  language: string | null;
  onboarding_completed: boolean | null;
  openness_level: string | null;
  password_hash: string | null;
  updated_at: Generated<Timestamp | null>;
  visual_onboarding_completed: boolean | null;
}

export interface Proposals {
  created_at: Generated<Timestamp | null>;
  dimension: string | null;
  from_user_id: Generated<string | null>;
  id: Generated<string | null>;
  scene_id: Generated<string | null>;
  status: string | null;
  to_user_id: Generated<string | null>;
}

export interface PsychologicalProfiles {
  correlations_detected: Json | null;
  id: Generated<string | null>;
  profile_signals: Json | null;
  test_scores: Json | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface SavedStorageImages {
  filename: string | null;
  id: Generated<string | null>;
  saved_at: Generated<Timestamp | null>;
}

export interface SceneResponses {
  answer: Json | null;
  created_at: Generated<Timestamp | null>;
  element_responses: Json | null;
  elements_selected: string[] | null;
  follow_up_answers: Json | null;
  id: Generated<string | null>;
  liked: boolean | null;
  profile_updates: Json | null;
  question_asked: string | null;
  question_type: string | null;
  rating: number | null;
  scene_id: Generated<string | null>;
  scene_slug: string | null;
  skipped: boolean | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface Scenes {
  accepted: boolean | null;
  ai_context: Json | null;
  ai_description: Json | null;
  allow_other: boolean | null;
  alt_for_gender: string | null;
  body_map_activity_config: Json | null;
  category: string | null;
  clarification_for: string[] | null;
  context: string | null;
  created_at: Generated<Timestamp | null>;
  elements: Json | null;
  follow_up: Json | null;
  for_gender: string | null;
  gates_scenes: string[] | null;
  generation_prompt: string | null;
  id: Generated<string | null>;
  image_options: Json | null;
  image_prompt: string | null;
  image_url: string | null;
  image_variants: Json | null;
  intensity: number | null;
  is_active: boolean | null;
  is_onboarding: boolean | null;
  onboarding_order: number | null;
  other_placeholder: Json | null;
  paired_questions: Json | null;
  paired_scene: string | null;
  paired_with: Generated<string | null>;
  priority: number | null;
  prompt_instructions: string | null;
  qa_attempts: number | null;
  qa_last_assessment: Json | null;
  qa_status: string | null;
  question: Json | null;
  role_direction: string | null;
  scene_type: string | null;
  selected_variant_index: number | null;
  sets_gate: string | null;
  shared_images_with: Generated<string | null>;
  slug: string | null;
  subtitle: Json | null;
  tags: string[] | null;
  text_options: Json | null;
  title: Json | null;
  user_description: Json | null;
  user_description_alt: Json | null;
  version: number | null;
}

export interface Subscriptions {
  created_at: Generated<Timestamp | null>;
  current_period_end: Timestamp | null;
  id: Generated<string | null>;
  plan: string | null;
  status: string | null;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  user_id: Generated<string | null>;
}

export interface TagCategories {
  category_id: Generated<string | null>;
  id: Generated<string | null>;
  relevance: number | null;
  tag: string | null;
}

export interface TagPreferences {
  created_at: Generated<Timestamp | null>;
  experience_level: string | null;
  id: Generated<string | null>;
  intensity_preference: number | null;
  interest_level: number | null;
  role_preference: string | null;
  source_scenes: string[] | null;
  specific_preferences: Json | null;
  tag_ref: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface UserClarificationTracking {
  clarification_slug: string | null;
  id: Generated<string | null>;
  shown_at: Generated<Timestamp | null>;
  triggered_by_main: string | null;
  user_id: Generated<string | null>;
}

export interface UserDiscoveryProfiles {
  bottom_tags: Json | null;
  completion_percentage: number | null;
  exploration_zones: Json | null;
  generated_at: Generated<Timestamp | null>;
  give_receive_balance: Numeric | null;
  id: Generated<string | null>;
  matched_insights: Json | null;
  preferred_intensity: Numeric | null;
  primary_archetype: string | null;
  secondary_archetypes: string[] | null;
  top_tags: Json | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface UserFlowState {
  calibration_complete: boolean | null;
  give_receive_balance: Numeric | null;
  id: Generated<string | null>;
  preferred_intensity: Numeric | null;
  seen_categories: string[] | null;
  seen_scenes: string[] | null;
  tag_scores: Json | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface UserGates {
  activity_gates: Json | null;
  body_map_gates: Json | null;
  created_at: Generated<Timestamp | null>;
  gates: Json | null;
  onboarding_gates: Json | null;
  updated_at: Generated<Timestamp | null>;
  user_id: Generated<string | null>;
}

export interface DB {
  admin_settings: AdminSettings;
  ai_messages: AiMessages;
  analytics_events: AnalyticsEvents;
  body_map_responses: BodyMapResponses;
  categories: Categories;
  date_responses: DateResponses;
  dates: Dates;
  discovery_config: DiscoveryConfig;
  excluded_preferences: ExcludedPreferences;
  experience_responses: ExperienceResponses;
  hidden_storage_images: HiddenStorageImages;
  image_analysis: ImageAnalysis;
  orientation_wishlist: OrientationWishlist;
  partner_chat_messages: PartnerChatMessages;
  partnerships: Partnerships;
  preference_profiles: PreferenceProfiles;
  profiles: Profiles;
  proposals: Proposals;
  psychological_profiles: PsychologicalProfiles;
  saved_storage_images: SavedStorageImages;
  scene_responses: SceneResponses;
  scenes: Scenes;
  subscriptions: Subscriptions;
  tag_categories: TagCategories;
  tag_preferences: TagPreferences;
  user_clarification_tracking: UserClarificationTracking;
  user_discovery_profiles: UserDiscoveryProfiles;
  user_flow_state: UserFlowState;
  user_gates: UserGates;
}
